"""Generate docs/data.js from the committed analysis artifacts.

The article's figures are drawn from this file, so they cannot drift from the
measurements: re-run after any experiment whose numbers the page cites.

Aggregates only — per-rank means and histogram counts, never player rows.
`data/human/` stays local by policy, and the page has to be publishable.

    python tools/make_article_data.py
"""

import collections
import json
import pathlib
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "envs"))
sys.path.insert(0, str(ROOT))


def j(p):
    return json.loads((ROOT / p).read_text())


def curve(name, ykey="win_rate"):
    d = j(f"analysis/training_curves/{name}.json")
    entries = d["log"] if isinstance(d, dict) and "log" in d else d
    return [{"x": r["steps"], "y": r.get(ykey)} for r in entries]


def build():
    out = {}

    out["labelEfficiency"] = [
        {"n": r["labelled_games"], "human": round(r["human_fitted"], 4),
         "agent": round(r["agent_grid_zero_labels"], 4)}
        for r in j("analysis/tetris_sprint/label_efficiency.json")["curve"]]

    tv = j("analysis/tetris_sprint/transfer_verdict.json")
    out["baselines"] = {k: round(v, 3) for k, v in tv["baselines_no_model"].items()}
    out["fitted"] = {"coupled": 0.66, "grid": 0.927,
                     "humanCV": round(tv["human_fitted_cv"]["all_five"], 3)}

    out["cliff"] = [{"acc": r["accuracy"], "lines": r["lines"], "finish": r["finish"]}
                    for r in j("analysis/tetris_sprint/accuracy_cliff.json")["rows"]]

    rows = j("data/human/tetrio_sprint.json")["rows"]
    by = collections.defaultdict(list)
    for r in rows:
        by[r["rank_index"]].append(r)
    out["humanRanks"] = []
    for ri in sorted(by):
        g = by[ri]
        mean = lambda k: float(np.mean([x[k] for x in g if x.get(k) is not None]))
        out["humanRanks"].append({
            "rank": g[0]["rank"], "i": ri,
            "quad": round(mean("quad_rate"), 3), "pps": round(mean("pps"), 2),
            "inpc": round(mean("inputs_per_piece"), 2),
            "hold": round(mean("holds_per_piece"), 3),
            "time": round(mean("time_ms") / 1000, 1)})
    q = np.array([r["quad_rate"] for r in rows])
    out["humanQuad"] = {
        "p2": round(float(np.percentile(q, 2)), 3),
        "p98": round(float(np.percentile(q, 98)), 3),
        "hist": np.histogram(q, bins=20, range=(0, 1))[0].tolist()}

    grid = [r for r in j("analysis/minesweeper/beginner_grid.json")["rungs"]
            if r.get("three_bv_per_s") is not None]
    out["msGrid"] = [{"bvs": r["three_bv_per_s"], "safe": r["proven_safe_rate"],
                      "win": r["won"], "eps": r["epsilon"], "lat": r["latency"]}
                     for r in grid]

    from coldopen.tetris import HUMAN_COMPARABLE
    blob = np.load(ROOT / "analysis/tetris_sprint/agent_episodes.npz")
    X = blob["x"]
    pi = HUMAN_COMPARABLE.index("pps")
    hi = HUMAN_COMPARABLE.index("holds_per_piece")
    idx = np.linspace(0, len(X) - 1, 160).astype(int)
    out["sprintScatter"] = [[round(float(X[i, pi]), 3), round(float(X[i, hi]), 3)]
                            for i in idx]
    sp = np.array([r["three_bv_per_s"] for r in grid])
    ju = np.array([r["proven_safe_rate"] for r in grid])
    out["corr"] = {
        "sprint": round(float(np.corrcoef(X[:, pi], X[:, hi])[0, 1]), 2),
        "minesweeper": round(float(np.corrcoef(sp, ju)[0, 1]), 2)}

    out["beginnerCurve"] = curve("minesweeper_prob_beginner")
    out["dqnCurve"] = curve("minesweeper")
    return out


if __name__ == "__main__":
    data = build()
    dest = ROOT / "docs" / "data.js"
    dest.parent.mkdir(exist_ok=True)
    dest.write_text(
        "// Generated by tools/make_article_data.py from analysis/ artifacts.\n"
        "// Do not hand-edit: the figures must not be able to drift from the\n"
        "// measurements. Aggregates only, no player rows.\n"
        "const DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print(f"wrote {dest} ({dest.stat().st_size:,} bytes)")
